# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: SensorData.proto
# Protobuf Python Version: 4.25.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10SensorData.proto\x12\x05Proto\"\xa5\x02\n\nSensorData\x12\x11\n\ttimestamp\x18\x01 \x01(\r\x12,\n\x10\x62\x61rometerMessage\x18\x02 \x01(\x0b\x32\x10.Proto.BarometerH\x00\x12\x34\n\x14\x61\x63\x63\x65lerometerMessage\x18\x03 \x01(\x0b\x32\x14.Proto.AccelerometerH\x00\x12\x32\n\x13magnetometerMessage\x18\x04 \x01(\x0b\x32\x13.Proto.MagnetometerH\x00\x12-\n\x11gyroscoperMessage\x18\x05 \x01(\x0b\x32\x10.Proto.GyroscopeH\x00\x12\x32\n\x13thermocoupleMessage\x18\x06 \x01(\x0b\x32\x13.Proto.ThermocoupleH\x00\x42\t\n\x07message\"\x85\x01\n\tBarometer\x12\x15\n\rbaro_pressure\x18\x01 \x01(\x05\x12\x18\n\x10\x62\x61ro_temperature\x18\x02 \x01(\x05\x12\x33\n\x11sensorLoggingRate\x18\x03 \x01(\x0b\x32\x18.Proto.SensorLoggingRate\x12\x12\n\nLoggingIdx\x18\x04 \x01(\x05\"\x8b\x01\n\rAccelerometer\x12\x0f\n\x07\x61\x63\x63\x65l_x\x18\x01 \x01(\x05\x12\x0f\n\x07\x61\x63\x63\x65l_y\x18\x02 \x01(\x05\x12\x0f\n\x07\x61\x63\x63\x65l_z\x18\x03 \x01(\x05\x12\x33\n\x11sensorLoggingRate\x18\x04 \x01(\x0b\x32\x18.Proto.SensorLoggingRate\x12\x12\n\nLoggingIdx\x18\x05 \x01(\x05\"\x84\x01\n\x0cMagnetometer\x12\r\n\x05mag_x\x18\x01 \x01(\x05\x12\r\n\x05mag_y\x18\x02 \x01(\x05\x12\r\n\x05mag_z\x18\x03 \x01(\x05\x12\x33\n\x11sensorLoggingRate\x18\x04 \x01(\x0b\x32\x18.Proto.SensorLoggingRate\x12\x12\n\nLoggingIdx\x18\x05 \x01(\x05\"\x84\x01\n\tGyroscope\x12\x0e\n\x06gyro_x\x18\x01 \x01(\x05\x12\x0e\n\x06gyro_y\x18\x02 \x01(\x05\x12\x0e\n\x06gyro_z\x18\x03 \x01(\x05\x12\x33\n\x11sensorLoggingRate\x18\x04 \x01(\x0b\x32\x18.Proto.SensorLoggingRate\x12\x12\n\nLoggingIdx\x18\x05 \x01(\x05\"r\n\x0cThermocouple\x12\x19\n\x11termo_temperature\x18\x01 \x01(\x05\x12\x33\n\x11sensorLoggingRate\x18\x02 \x01(\x0b\x32\x18.Proto.SensorLoggingRate\x12\x12\n\nLoggingIdx\x18\x03 \x01(\x05\"L\n\x11SensorLoggingRate\x12\x19\n\x11\x63hangeLoggingRate\x18\x01 \x01(\x08\x12\x1c\n\x14newSensorLoggingRate\x18\x02 \x01(\rb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'SensorData_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_SENSORDATA']._serialized_start=28
  _globals['_SENSORDATA']._serialized_end=321
  _globals['_BAROMETER']._serialized_start=324
  _globals['_BAROMETER']._serialized_end=457
  _globals['_ACCELEROMETER']._serialized_start=460
  _globals['_ACCELEROMETER']._serialized_end=599
  _globals['_MAGNETOMETER']._serialized_start=602
  _globals['_MAGNETOMETER']._serialized_end=734
  _globals['_GYROSCOPE']._serialized_start=737
  _globals['_GYROSCOPE']._serialized_end=869
  _globals['_THERMOCOUPLE']._serialized_start=871
  _globals['_THERMOCOUPLE']._serialized_end=985
  _globals['_SENSORLOGGINGRATE']._serialized_start=987
  _globals['_SENSORLOGGINGRATE']._serialized_end=1063
# @@protoc_insertion_point(module_scope)
