# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: CommandMessages.proto
# Protobuf Python Version: 4.25.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x15\x43ommandMessages.proto\x12\x05Proto\"c\n\x0f\x43ommandMessages\x12\x1b\n\x13source_sequence_num\x18\x01 \x01(\r\x12(\n\x0b\x66sb_command\x18\x02 \x01(\x0b\x32\x11.Proto.FsbCommandH\x00\x42\t\n\x07message\"|\n\nFsbCommand\x12.\n\x0b\x66sb_message\x18\x01 \x01(\x0e\x32\x19.Proto.FsbCommand.Command\">\n\x07\x43ommand\x12\x11\n\rSTART_LOGGING\x10\x00\x12\x10\n\x0cSTOP_LOGGING\x10\x01\x12\x0e\n\nSEND_FILES\x10\x02\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'CommandMessages_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_COMMANDMESSAGES']._serialized_start=32
  _globals['_COMMANDMESSAGES']._serialized_end=131
  _globals['_FSBCOMMAND']._serialized_start=133
  _globals['_FSBCOMMAND']._serialized_end=257
  _globals['_FSBCOMMAND_COMMAND']._serialized_start=195
  _globals['_FSBCOMMAND_COMMAND']._serialized_end=257
# @@protoc_insertion_point(module_scope)
