/**
  ******************************************************************************
  * @file     lib.c
  * @author   Auto-generated by STM32CubeIDE
  * @version  V1.0
  * @date     16/11/2024 10:47:31
  * @brief    Default under dev library file.
  ******************************************************************************
*/

/* Includes ------------------------------------------------------------------*/
#include "stm32h7xx_hal.h"


#include "C://Users//diogo//STM32CubeIDE//workspace_1.16.1//I2C_Wrapper//Src//I2C_Wrapper.h"

/** Functions ----------------------------------------------------------------*/
uint8_t I2C_writeReg(I2C_INTERFACE *interface){
	uint8_t status;
	uint8_t temp_send[255];
	temp_send[0] = interface->register_address;
	memcpy(&temp_send[1], interface->send_data, interface->num_bytes);
	/*
	for (int i = 0; i < interface->num_bytes; i++) {
	    temp_send[i + 1] = interface->send_data[i];
	}
	*/
	status = HAL_I2C_Master_Transmit(interface->hi2c, interface->device_address, temp_send, interface->num_bytes + 1, 1000); //resend
	if(status != HAL_OK)
		return status;

	//Confirming the data

	status = HAL_I2C_Master_Transmit(interface->hi2c, interface->device_address, interface->register_address, 1, 1000); //Send the register address
		if(status != HAL_OK)
			return status;
	HAL_Delay(50); //Double check if this actually needed
	status = HAL_I2C_Master_Receive(interface->hi2c, interface->device_address , interface->received_data, interface->num_bytes, 1000); //Listen for the value stored
	if(status != HAL_OK)
			return status;

	for(int i=0; i<interface->num_bytes; i++){ // Check the data match what was sent
		if(interface->send_data[i] != interface->received_data[i]){
			return COMM_ERROR;
		}
	}
	return HAL_OK;
}
